name: Build OpenSK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch of openSK repository'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y uuid-runtime python3 python3-pip libssl-dev git curl

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Clone OpenSK repository
        run: git clone https://github.com/google/OpenSK.git
        
      - name: Build OpenSK 
        run: |
          cd ./OpenSK
          ./setup.sh
          ././deploy.py --board=nrf52840_dongle_dfu --opensk --programmer=none
