name: build openSK

on: workflow_dispatch

jobs:
  build:
    runs-on: debian:stable-slim

    steps:
      - name: install uuid-runtime
        run: apt install uuid-runtime
        
      - name: install Python3 and pip
        run: apt install python3 python3-pip

      - name: install openSSL
        run: apt install libssl-dev

      - name: install rustup
        run: |
          apt install wget
          wget https://sh.rustup.rs
          ./rustup-init.sh

      - name: install git
        run: apt install git

      - name: clone openSK repository
        run: git clone https://github.com/google/OpenSK.git
